### PR TITLE
temp fix for breaking php5.4 compatibility

### PR DESCRIPTION
**Pull request by weemen**

### CODE REVIEW

**Comment by marcojanssen** [comment]
What php version is required? no version is mentioned in composer?

**Comment by weemen** [comment]
Unfortunately we will have to keep it php 5.4 compatible for now but I think as soon as we can make the jump to 5.5 then we keep it compatible for that version. It's a bit unsure for now.

Note: I'll put the php version for composer on my todo list.

**Comment by marcojanssen** [comment]
Unsure? php 5.4 is end of life in September :) No real reason to be in doubt about the required version

**Comment by weemen** [comment]
Well its clear for us that php5.4 is not our target version. This fix is temporary and hopefully gone soon. The unclearity is more in what our target version is going to be. We didnt discuss it. Thats why it is unclear.

**Pull request merged**
